- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables, global variables
    COURSE: "DevOps and linux"
    DURATION: 120hRS
    TRAINER: Shiva
  tasks:
  - name: Print the variable
    vars: 
     COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print the variable1
    vars_files
  - course.yaml
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: Print the variable2
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"