- name : variables from files
  hosts:  local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: Please enter course 
      private: false #its used for non-confidential
    - name: DURATION
      prompt: Please enter duration 
      private: false
    - name: TRAINER
      prompt: please enter Trainer name
      private: false
  tasks:
       - name : print course information
         ansible.builtin.debug:
           msg: "Course is {{ COURSE }}, DURATION is {{ DURATION }} ,  Trainer is {{ TRAINER}}"