- name: shell vs Command
  hosts: local
  connection : local
  tasks:
  - name: execute ls command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    #ansible.builtin.shell: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: df -h > /tmp/df1.txt
    ansible.builtin.command: df -h
    register: command_result

  - name: Print the output
    ansible.builtin.debug:
     msg: "{{ command_result }}"